### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by Sushestvo16** [Sushestvo16/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by Sonyamonya22** [comment]
<h1>**DONALD TRUMP**</h1>

https://www.donaldjtrump.com/ 
https://twitter.com/donaldtrump
https://www.facebook.com/DonaldTrump/
